### ISSUE TITLE
Mod packs which lack icons

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Crzyrndm/FilterExtension#15]
Most of the big part mods have icons for them, but mods without icons show up as question marks (or not at all, in the raw dll on the repo as of this posting).  It would be cool to put a mod's initials on the tab if there's no icon (like @blacknecro's [PartCatalog](https://github.com/blacknecro/partcatalog), but the other solution of course is to make more icons.  Looking at my (heavily mod-laden) 0.25 install, as well as recalling mods I've considered using or seen around, here are some part mod folders which don't yet have icons.  Given how many there are (and there will undoubtedly be more), it would probably be easiest to make some initial-generating code (or fix the lack-of-question-marks bug), but feel free to knock a few out on a rainy day (I've got some ideas for some already), especially the ones which are compatible with 0.90 or that you use personally.

(Regarding links; I put the link in the folder name when it's the name of the mod.  Not every mod folder matches its name, though.)

- [ ] 0PinlineFairings, [Zero-Point Inline Fairings](http://forum.kerbalspaceprogram.com/threads/94427)
- [x] ASET, various lander and exploration parts, including the [ALCOR](http://forum.kerbalspaceprogram.com/threads/54925) 3-kerbal lander can
- [ ] [AviationLights](http://forum.kerbalspaceprogram.com/threads/16925), what it sounds like
- [x] BAE, [Behemoth Aerospace Engineering](http://forum.kerbalspaceprogram.com/threads/124064-Behemoth-Aerospace-Engineering-Large-Parts-v1-1-0-%282015-06-05%29)
- [ ] BahamutoD, miscellaneous parts from [Bahamuto Dynamics](http://forum.kerbalspaceprogram.com/threads/49035) including a shielded Clamp-O-Tron Sr. and dockable fairings.
- [x] BahaSP, various [Animated and Retractable Engines](http://forum.kerbalspaceprogram.com/threads/82341)
- [ ] [BDArmory](http://forum.kerbalspaceprogram.com/threads/85209), weapons and such.
  - These three are all made by BahamutoD, maybe they could all get sorted under the same manufacturer (and thus one icon for all of them -- there's a nifty "BD" icon in the BahaSP thread) the way that the various NearFutureX mods are.
- [ ] [BoxSat](http://forum.kerbalspaceprogram.com/threads/91616) alpha, totally-not-Cubesats.
- [ ] [CactEye](http://forum.kerbalspaceprogram.com/threads/105660) Orbital Telescopes
- [ ] [CargoTransferBags](http://forum.kerbalspaceprogram.com/threads/70986), EVA-portable resource tanks for TAC-LS (maybe could be sorted under TAC-LS?)
- [ ] [Firespitter](http://forum.kerbalspaceprogram.com/threads/24551), propeller airplane and helicopter parts
- [x] [Hangar](http://forum.kerbalspaceprogram.com/threads/88933), vessel storage
- [ ] [HexCans](http://forum.kerbalspaceprogram.com/threads/33754), standardized resource cannisters
- [ ] HGR and HGR_Redux, [Home Grown Rockets](http://forum.kerbalspaceprogram.com/threads/60974-1-0-2-HGR-1-875m-parts(v1-3-0-released)) (1.875m parts)
- [ ] [HoloTape](http://forum.kerbalspaceprogram.com/threads/83791), holographic measuring tape.  Could it be sorted under USI?  It's not distributed as part of the "USI_ALLMODS" package, though...
- [ ] [HooliganLabs](http://forum.kerbalspaceprogram.com/threads/53961), airship and submarine parts
- [ ] [HullCameraVDS](http://forum.kerbalspaceprogram.com/threads/46365), various external cameras.
- [ ] KASA, [IXS Class Warpship and Spacedocks](http://forum.kerbalspaceprogram.com/threads/92816).
- [ ] KashCorp, [Rovers and Roadsters](http://forum.kerbalspaceprogram.com/threads/87546-0-25-Rovers-And-Roadsters) ground vehicle parts.
- [ ] KipEng, [Kip Engineering](http://forum.kerbalspaceprogram.com/threads/73005) Universal Docking Ports and Low Profile Structural Hubs.
- [ ] M22Ind, [radial stack separator](http://forum.kerbalspaceprogram.com/threads/91964)
- [ ] masTerTorch, [Kerbal Dust EXperiment](http://forum.kerbalspaceprogram.com/threads/54656)
- [ ] MEPS, [Multipurpose Express Pallet System](http://forum.kerbalspaceprogram.com/threads/92684)
  - [ ] And SPFloor (same mod)
- [ ] Mk2Essentials, MkIVEssentials -- not official names, but JoePatrick1 has made a bunch of miscellaneous Mk2 and MkIV parts (separator, decoupler, battery).
  - [ ] LargeSolarWings, [Solar Panel Wings](http://forum.kerbalspaceprogram.com/threads/83504) by the same guy.
  - [ ] BfS, [Banana for Scale](http://forum.kerbalspaceprogram.com/threads/89570) by the same guy.
  - [ ] CORE, [Complete Octagonal Rocketry Expansion](http://forum.kerbalspaceprogram.com/threads/91583), octagonal probe parts, same guy
  - [ ] [m8](http://forum.kerbalspaceprogram.com/threads/89555), a small probe engine, same guy.
- [x] [OPT](http://forum.kerbalspaceprogram.com/threads/97525) wide-body space plane parts
- [ ] PaladinLabs, [DeepFreeze](http://forum.kerbalspaceprogram.com/threads/92806) cryonic crew storage
- [x] R&SCapsuledyne, [Taurus HCV](http://forum.kerbalspaceprogram.com/threads/75074) (big crew capsules)
- [ ] RadialEngineMountsPPI, [Radial Engine Mounts](http://forum.kerbalspaceprogram.com/threads/92278) -- what it sounds like
- [ ] [RoverScience](http://forum.kerbalspaceprogram.com/threads/75059), only one part, but still!
- [ ] [SDHI](http://forum.kerbalspaceprogram.com/threads/52362) Service Module System
- [ ] SockeAA, [Socke's 1.875m Expansion](http://forum.kerbalspaceprogram.com/threads/98456-WIP-Socke-s-Parts-1-875m-Extension)
- [x] SpaceY-Lifters, [SpaceY Heavy Lifter](http://forum.kerbalspaceprogram.com/threads/100408) parts pack
- [x] SPD, [Speedy's Hex Truss System](http://forum.kerbalspaceprogram.com/threads/86388)
- [x] SurfaceLights, [Surface Mounted Stock-Alike Lights](http://forum.kerbalspaceprogram.com/threads/57778)
- [ ] TouhouTorpedo, [TT's SPP Mk2 Nose](http://forum.kerbalspaceprogram.com/threads/98854)
- [x] [TurboNisuReloaded](http://forum.kerbalspaceprogram.com/threads/102041-0-90-TurboNisuReloaded-Stock-a-Like-Parts-Pack-22-1-14)
- [ ] [WarpShip](http://forum.kerbalspaceprogram.com/threads/120454-WIP-1-0-2-WarpShip-0-3-1-Update-expansion-of-IXS-Enterprise)
- [ ] WildBlueIndustries, [Multipurpose Colony Modules](http://forum.kerbalspaceprogram.com/threads/98251) for MKS/OKS.
- [x] WombatConversion, various parts for [EPL to Regolith Conversion](http://forum.kerbalspaceprogram.com/threads/89774)
- [ ] WorldCup2014 [Kerbin Cup](http://forum.kerbalspaceprogram.com/content/286) (official mod)
- [ ] XanderTek, [XT Landertrons](http://forum.kerbalspaceprogram.com/threads/61294)
- [x] Yarbrough08, [Mk1-1 A2 command pod](http://forum.kerbalspaceprogram.com/threads/98250)
- [x] ZZZ_Flags, flag decals from [SciFi Shipyards](http://forum.kerbalspaceprogram.com/threads/37908)

**Comment by KaiserSoze** [comment]
OMG. And I though I had a heavy modded ksp :P.
I can create fast icons with just the initials in no time (almost) and with more time I will be creating icons for the rest. With the link I can download it and also look for inspiration, so thank you for that.

Not today though, I had an issue with B9 and I have to nail if there is a bug there or an incompatibility with my other mods.

Keep this issue open until the icons are created.

**Comment by Kerbas-ad-astra** [comment]
I was thinking it would be better to have the mod itself make initials, the way that PartCatalog used to, so that we don't need to make and push out a new icon (even a simple one) for each new part pack that comes along.

**Comment by KaiserSoze** [comment]
Nor really sure. Also I'm sure if making the mod showing the initials is an option. right now I simply cannot do it. I would have to study part catalog code to see how it was done.

Any case I think it would be better than the question marks. Ideally it should use icon if there is one or initials if there is not. I will have a look at PC code to see if I can get any idea.

**Comment by Crzyrndm** [comment]
I wouldn't bother Kaiser, I have an ingame cfg/icon selector/creator (reduced chance of typo's, easier to just throw a few icons into place) in the works so I can just add that to the list of features it will need

**Comment by KaiserSoze** [comment]
GREAT!
So, there is no rush for create icons with just letters. I will still be creating icons, but that way small pack will at least have something.

So I will still be fighting with B9 and narrowing which mod that I have causes one part to call the kraken. I really hate debugging.

**Comment by KaiserSoze** [comment]
Wombat is done.

**Comment by Kerbas-ad-astra** [comment]
For future reference, I made the mods all have checkboxes, so you can check them off as you complete them.

**Comment by LouisB3** [comment]
Couple more for the scoreboard...

- [ ] [Kerbal Atomics](http://forum.kerbalspaceprogram.com/index.php?/topic/130503-105-kerbal-atomics-fancy-nuclear-engines-20022016-fixes-nfe-support/)
- [ ] Asteroid Day (though only the telescope part will be non-stock in 1.1)
