### ISSUE TITLE
Resources which lack icons

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Crzyrndm/FilterExtension#17]
There are too many for me to type out, but there are a bunch, and I think that [Alternate Resource Panel](http://forum.kerbalspaceprogram.com/threads/60227) icons would be a good place to start.  Also [these icons](http://forum.kerbalspaceprogram.com/threads/102980-v0-4-1-KSP-Alternate-Resource-Panel-Icon-Overhaul) by @Olympic1 (source in [this repo here](https://github.com/Olympic1/Icon_Packs_KSP)), licensed under CC-BY-NC-SA.

EDIT: Does this mod by default use whatever icon has the same name as the texture?  If so, and if 32x16 textures don't get stretched, we might not even have to adapt them, just make those ARP icons a recommended download.  Alternatively, it seems that ARP also has a system for designating icons to be associated with resources.

The downside is that those icons are very colorful -- fine on ARP, but maybe not so desirable for fitting in with the editor.  We could make greyscale non-selected versions, but then we might as well adapt them completely and make a set to include within this mod.

**Comment by Crzyrndm** [comment]
We've already had problems with it accidentally picking up ARP's resource icons and stretching them. It's the reason the icons have a minimum dimension of 25 pixels

**Comment by KaiserSoze** [comment]
Don't bother. They need more work than auto reshape, we have to play with transparency. because otherwise they will show a big black shadow.
I will use them as a base for the icons. This was my next step :P

**Comment by Olympic1** [comment]
I don't want to be a bitch, but if you use my pack icons you have to include a BY-NC-SA license. If you use the icons of ARP you have to include the MIT license. I just want to prevent some license trouble.

**Comment by KaiserSoze** [comment]
Don't worry, I understand you. As you may have said license is already BY-NC-SA and we were saying something similar in other issue about so it's being work out. Or so I think.

BTW: We should have to include the names of part catalog author (BlackNecro)  and icon maker (toerti). Their license was CC-SA, so It's not so critical, but I think it's just polite to at least mention them.

**Comment by Olympic1** [comment]
agreed

**Comment by KaiserSoze** [comment]
BTW: This means you will do the conversion from you icons to this format (32x32)?. It could save me a lot of time :P. Even making them similar still takes time so any help if welcome. 

Also you may prefer to do the conversion your way and be screaming at my poor attempts to use those icons (I'm far from a graphic designer, just prefer poor icons to question marks)

**Comment by Olympic1** [comment]
I didn't yet look at the icons for the VAB so let me see how it works and I'll begin working on it.

**Comment by KaiserSoze** [comment]
Good. If you do them I could go for the module icons

**Comment by KaiserSoze** [comment]
Did you have a chance to have a look at them?
If you are busy I can keep converting your resource icons to this format, but I do not want to have us both working in the same thing.

**Comment by Olympic1** [comment]
Yes, I had a look at it but haven't made much progress because of school and I want to update the BioMass mod for 0.90.

You can keep converting them. I uploaded a new icon for BioMass you can find it [here](https://github.com/Olympic1/Icon_Packs_KSP/blob/master/GameData/Olympic1ARPIcons/USIPack/Textures/BioMass.png)

**Comment by Olympic1** [comment]
I just want to be recognized for the icons somewhere (readme, my license, ...), you can choose where and how.

**Comment by KaiserSoze** [comment]
You will be recognized, after all most the icons will be just conversion from the ones you have already made.
Not to mess with this issue but I'm glad biomass is being updated :)
