### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by phmayo** [Crzyrndm/FilterExtension#19]
Rather than dig through the commits, what about a changelog? IIRC, git or GitHub has a means to automagically generate something like that.

**Comment by Crzyrndm** [comment]
Changelog can be found in the first post of the release thread on KSP forums [here](http://forum.kerbalspaceprogram.com/threads/104231-0-90-Filter-Extensions-1-12-%28Jan-4%29) and version specific changes are always posted around the time I put a release out (eg. [1.11 release notes](http://forum.kerbalspaceprogram.com/threads/104231-0-90-Filter-Extensions-1-12-%28Jan-4%29?p=1643573&viewfull=1#post1643573))
