### ISSUE TITLE
Disabled parts appear in "Passengers"

### ISSUE THREAD

**Issue by lwho** [Crzyrndm/FilterExtension#24]
Using FilterExtension 1.15.2 installed via CKAN, I noticed, that some parts appeared in "Kerbonauts and Control" -> "Passengers" and "Kerbonauts and Control" -> "Multiple Kerbals" that shouldn't appear there.

I started a fresh sandbox game to see all parts and thus found out, that all of those parts have in common that they should not appear at all in the VAB parts list (i.e. should not be buildable at all).

For me those parts are

1. "A potato like rock" (NASAmission/Parts/PotatoRoid/part.cfg). Seems to be a stock "part" that obviously shouldn't be buildable.

2. "0.625m Fairing Base", "0.625m Fairing Base Ring" (and those for 1.25m, 2.5m, 5m). Those are of the Procedural Fairings mod.
Normally, you have only "Fairing Base", "Fairing Base Ring" available and get the various sizes from the right-click tweaking menu. Indeed only those appear in "Filter by Manufacturer" -> "ProceduralFairings".

3. Interstage Fairing Adapter (also from ProceduralFairings)
While a part of the same name exists in "Filter by Manufacturer" -> "ProceduralFairings", they don't have the same specs. So, I assume the one in "Kerbonauts and Control" is also a disabled one.

4. Various parts named "Procedural Fairings Upgrade" (from ProceduralFairings). Those seem to be also internal parts that shouldn't be accessible directly.

5. SCAN MapTraq (ScanSat mod). This is a part that is normally not present in the current version of ScanSat.

I guess, the inverted crew check doesn't work for those disabled parts for some reason. Given that the first one (the rock) is a stock part and assuming it's the same bug for all those parts, this should be reproducible without the mods, I hope.

I'm using the x86_64 Linux version of KSP 0.90.0 if that matters.

I did not find anything relevant in Player.log.

Great Mod, BTW. It's just what I was still missing.

**Comment by Crzyrndm** [comment]
Oh that was silly of me.

Check for parts with no category has been moved so it can't be inverted. Issue resolved

**Comment by lwho** [comment]
Great! Thanks for the fast update! It seems to work now.
