### ISSUE TITLE
Suggested license change, CC-BY-NC -> GPL v3

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Crzyrndm/FilterExtension#26]
[Creative Commons themselves suggest not using CC licenses on software.](https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F)  The GPL v3 keeps the share-alikeness, adds some extra freedom goodness with respect to software-specific issues (e.g. source code availability, patents, and DRM), and is a little more straightforwardly compatible with more software projects.  (EDIT: the attribution bit is also covered, in that forks must "keep intact all notices" of copyright, and requiring attribution also falls under the permitted "additional terms" of the GPL, e.g. "Prohibiting misrepresentation of the origin of that material, or requiring that modified versions of such material be marked in reasonable ways as different from the original version.")  The only "loss" compared to CC-BY-NC is the restriction against non-commercial use, but I figure if somebody figures out a way to make money on something you're giving away for free, more power to 'em.  ;)  In all seriousness, YouTube videos are commercial derivative works, especially when the creator gets paid, as some of the higher-profile ones are.

(The CC license family does make plenty of sense for art assets, like the icons, though I'd suggest losing the -NC where it's possible, for the same reason as above.)

**Comment by Olympic1** [comment]
It is allowed to have multiple license for a mod. Keep the GPL v3 license for the software and the CC BY-NC license for the icons.

**Comment by Crzyrndm** [comment]
Honestly I'm not too concerned with the license for the plugin. I have one because the forum requires it and that's about it. If GPL covers the plugin better then I don't have any real argument against changin it

**Comment by Crzyrndm** [comment]
License changes made as recommended 
License for icons is now CC-BY-SA 4.0
License for plugin is now GPL v3
