### ISSUE TITLE
Option to not automatically set advanced mode

### ISSUE THREAD

**Issue by Crzyrndm** [Crzyrndm/FilterExtension#34]
http://forum.kerbalspaceprogram.com/threads/104231-1-0-x-Filter-Extensions-2-2-1-%28May-25%29?p=1983793&viewfull=1#post1983793

Users with narrow screens and/or low resolutions may not want to decrease available editor space further

**Comment by BevoLJ** [comment]
I vaguely remember using a config option for this a while back, but can't seem to find it on a new install.  Is there a config option to set it to normal mode by default?
