### ISSUE TITLE
Packaging goof?

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Crzyrndm/FilterExtension#42]
I added a new size category a month ago (for KPBS, PR #41), but it isn't included in the 2.4.1.1 release (in the configs or the icon).

Other stuff isn't right either --  GameData/000_FilterExtensions/Icons/Autoloaded_Icons_Mods/000_Mods.txt is still present when it was removed in commit 438f204d613e8320de3f4e82e6e35bdf30dbe403.

**Comment by Crzyrndm** [comment]
Er, let me just go poke that...

**Comment by Crzyrndm** [comment]
Looks like I forgot to synch my local version with github before packaging the release. Packaging goof would be a fairly apt description methinks >.>
