### ISSUE TITLE
Settings.cfg and ModuleManager

### ISSUE THREAD

**Issue by Schnobs** [Crzyrndm/FilterExtension#47]
ModuleManager will rebuild it's ConfigCache whenever something changes in the Gamedata directory. It ignores folders named "PluginData" and everything inside, but any other changed file will trigger a cache rebuild.

GameData/000_FilterExtensions/Settings.cfg updates it's modification time on every startup; given it's place in the alphabet, I'm afraid this happens before MM gets to look for changed files.

Is it necessary that this file gets rewritten, *and* has to sit in a place where ModuleManager considers it for purposes of cache validation?

**Comment by Crzyrndm** [comment]
I'm aware of the issue and am planning on moving all transient files for all of my plugins inside pluginData in post-1.1 updates

**Comment by Crzyrndm** [comment]
40df0a2f051fc61f4382698ae12260fc868ee3ce includes the above mentioned changes if you want them now
