### ISSUE TITLE
CKAN integration

### ISSUE THREAD

**Issue by plague006** [Crzyrndm/FilterExtension#57]
Traditionally CKAN has indexed FilterExtensions in a modular fashion with `FilterExtension` as the base mod with `FilterExtensionsDefaultConfig` and `FilterExtensionsStockRework` extending functionality by installing the `000_FilterExtensions Configs` and `000_FilterExtensions Configs/StockRework` folders respectively. In the latest release instead of a StockRework folder there's a .zip (CKAN is unable to unzip a file inside a mod .zip). So with the background out of the way I'm inquiring as to whether this is something that will be changed in future versions or if this is how the mod's packaging will remain.

Thanks.

**Comment by Crzyrndm** [comment]
Stock rework needs a number of config updates, which I haven't got to yet. Next release (before the end of the weekend) will fix these issues and normal distribution style will return

**Comment by plague006** [comment]
Perfect thanks for the heads up. CKAN will automatically index the new release when it's done so I'll happily close this.
