### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by RealKolago** [Crzyrndm/FilterExtension#65]
FilterExtensions does not work (doesn't show up) and NullReferenceException

Full Log: https://mega.nz/#!rwtQQJbR!INH47g23TxPXFKB_bZQLs99AaIMkWk2Lsizn8gSjYNk

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.MonoBehaviour:StartCoroutine_Auto (System.Collections.IEnumerator)
  at UnityEngine.MonoBehaviour.StartCoroutine (IEnumerator routine) [0x00000] in <filename unknown>:0 
  at FilterExtensions.Editor.StartEditor () [0x00000] in <filename unknown>:0 
  at EventVoid.Fire () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
EventVoid:Fire()
KSP.UI.Screens.<SetInitialState>c__Iterator123:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
KSP.UI.Screens.PartCategorizer:Setup()
EventVoid:Fire()
KSP.UI.Screens.EditorPanels:ShowPartsList(Action)
EditorLogic:SelectPanelParts(Boolean)
EditorLogic:StartEditor(Boolean)
<Start>c__Iterator30:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by Crzyrndm** [comment]
Should be fixed (here)[https://github.com/Crzyrndm/FilterExtension/tree/master/GameData/000_FilterExtensions]. If you could please verify that this change resolves the issue

**Comment by RealKolago** [comment]
Still a NullReferenceException with the new DLL.

Full Log: https://mega.nz/#!680xBRrK!C5-SIWpdRBL_xtGMXxHLjBq1jf5IUc5Rum3WoDvOS84

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.MonoBehaviour:StartCoroutine_Auto (System.Collections.IEnumerator)
  at UnityEngine.MonoBehaviour.StartCoroutine (IEnumerator routine) [0x00000] in <filename unknown>:0 
  at FilterExtensions.Editor.StartEditor () [0x00000] in <filename unknown>:0 
  at EventVoid.Fire () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
EventVoid:Fire()
KSP.UI.Screens.<SetInitialState>c__Iterator123:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
KSP.UI.Screens.PartCategorizer:Setup()
EventVoid:Fire()
KSP.UI.Screens.EditorPanels:ShowPartsList(Action)
EditorLogic:SelectPanelParts(Boolean)
EditorLogic:StartEditor(Boolean)
<Start>c__Iterator30:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by Crzyrndm** [comment]
Latest commit fixes an issue that appears to be what caused this. If you could test again

**Comment by RealKolago** [comment]
Looks fixed to me. Thanks!
