### ISSUE TITLE
FilterExtension 2.8.1 eats non-Pod parts

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Crzyrndm/FilterExtension#69]
Starting a test install of KSP 1.2.2 with FilterExtension 2.8.1 and nothing else, going into the editor I find that only the pod category has anything.  Fuel tanks, engines, etc. all gone.  When filtering by e.g. cross-section, same story -- it only shows *pods* of the relevant size.  This doesn't happen with FE 2.8.0.2.

The log only has this (out of the ordinary) to say: "UIList: RemoveItem didn't find any item to remove."

**Comment by RealKolago** [comment]
I can confirm this issue.

**Comment by Crzyrndm** [comment]
New version is up with a fix for this issue
