### ISSUE TITLE
FE 3.0.0 (doesn't show up) vs 2.8.1.2

### ISSUE THREAD

**Issue by khr15714n** [Crzyrndm/FilterExtension#72]
It's a minimal install for testing.

![](https://s7.postimg.org/x0lwgb07f/FE_3.0.0_vs_2.8.1.2.png)

excerpt of ksp.log containing all FE entries: only the first line is visible using 2.8.1.2

[WRN 10:27:28.459] [Filter Extensions 3.0.0.0]: 
[LOG 10:27:28.488] [ModuleManager] Total loading Time = 30.793s
[LOG 10:27:28.561] [ApplicationLauncher] Awake False
[LOG 10:27:28.563] [ApplicationLauncher] SpawnSimpleLayout: VerticalTopDown
[LOG 10:27:28.574] [UiApp] Awake: MessageSystem
[LOG 10:27:28.575] [ApplicationLauncher] OnSceneLoadedGUIReady: scene MAINMENU ShouldBeVisible() True ShouldBeOnTop() True iIsPositionedAtTop True
[LOG 10:27:28.649] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Liquid Fuel
[LOG 10:27:28.650] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Oxidizer
[LOG 10:27:28.651] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Ablator
[LOG 10:27:28.651] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Electric Charge
[LOG 10:27:28.652] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Intake Air
[LOG 10:27:28.652] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Mono Propellant
[LOG 10:27:28.653] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Solid Fuel
[LOG 10:27:28.654] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Xenon Gas
[LOG 10:27:28.654] [Filter Extensions 3.0.0.0]: resource name already exists, abandoning generation for Ore
[WRN 10:27:28.675] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.676] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.676] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.677] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.678] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.678] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.679] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.680] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.680] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.681] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.682] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.682] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.683] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.683] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.684] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[WRN 10:27:28.685] [Filter Extensions 3.0.0.0]: Could not load type 'KSP.Localization.Localizer' from assembly 'FilterExtensions'.
[LOG 10:27:28.721] [UIApp] Adding MessageSystem to Application Launcher
[LOG 10:27:28.732] [ApplicationLauncher] SetHidden: 
[LOG 10:27:28.753] [MessageSystem] OnAppInitialized
[LOG 10:27:28.755] [MessageSystem] Reposition 0.125647 32274
[LOG 10:27:40.261] [ReflectionUtil]: Found 4 types with UpgradeModule attribute in 11 assemblies.
[LOG 10:27:40.273] [KSPUpgradePipeline]: default (1.2.2) is up to date.
[LOG 10:27:40.279] [ExperienceSystem]: Found 0 trait types
[LOG 10:27:40.282] [ExperienceSystem]: Found 25 effect types
[WRN 10:27:40.290] [GameParameters]: Couldn't find type for custom parameter FESettings.
[LOG 10:27:40.308] [ScenarioTypes]: List Created 18 scenario types loaded from 11 loaded assemblies.
[LOG 10:27:40.311] [UIMasterController]: HideUI
[LOG 10:27:40.312] [HighLogic]: =========================== Scene Change : From MAINMENU to SPACECENTER (Async) =====================
[LOG 10:27:40.453] [AddonLoader]: Instantiating addon 'TRActivator' from assembly 'Texture Replacer'
[LOG 10:27:40.455] [UIMasterController]: HideUI
[LOG 10:27:41.305] [AddonLoader]: Instantiating addon 'ContractDefs' from assembly 'KSP'
[LOG 10:27:41.316] [AddonLoader]: Instantiating addon 'CustomConfigsManager' from assembly 'ModuleManager'
[LOG 10:27:41.317] [AddonLoader]: Instantiating addon 'FMRS_Space_Center' from assembly 'FMRS'
[LOG 10:27:41.321] windowPos loaded from file
[LOG 10:27:41.324] [AddonLoader]: Instantiating addon 'FMRS_Register' from assembly 'FMRS'
[LOG 10:27:41.325] [AddonLoader]: Instantiating addon 'RecoveryController' from assembly 'RecoveryController'
[LOG 10:27:41.327] [AddonLoader]: Instantiating addon 'TRActivator' from assembly 'Texture Replacer'
[LOG 10:27:41.327] [AddonLoader]: Instantiating addon 'TRGui' from assembly 'Texture Replacer'
[LOG 10:27:42.955] [UIMasterController]: HideUI
[WRN 10:27:43.017] [GameParameters]: Couldn't find type for custom parameter FESettings.
[................] [ScenarioDestructibles]: Loading... 0 objects registered
[LOG 10:27:46.204] [Filter Extensions 3.0.0.0]: Starting on general categories

**Comment by khr15714n** [comment]
Removed Kurrikane and dependencies (SoundingRockets, 000_USITools, FMRS, RecoveryController, TextureReplacer) and 3.0.0 looks like 2.8.1.2.
I'll try to figure out what rose the issue.

**Comment by khr15714n** [comment]
Complete fresh install, only +FE - same result.

**Comment by Olympic1** [comment]
v3.0 is build for KSP 1.3. If it cannot find `KSP.Localization.Localizer` you are probably not playing on 1.3 or have you ksp wrong installed

**Comment by Crzyrndm** [comment]
+1 for incorrect KSP version. Don't update if you're not updating KSP as well

**Comment by khr15714n** [comment]
Sorry, missed the 1.3 announcement and without starting steam there was no automatic update either.
