### ISSUE TITLE
Icons for Manufacturers

### ISSUE THREAD

**Issue by gomker** [Crzyrndm/FilterExtension#73]
I did a PR awhile back for some mods I support in which I specify Icons. Seems that the Manufacturer mappings are no longer working. The icons seem to be there but they are showing the ? icon

https://github.com/gomker/FilterExtension/blob/ddcb6039ca0afca3295a138c943713b8a248d73f/GameData/000_FilterExtensions%20Configs/Default/Mod_Naval.cfg

Do I need to update something further to make this work with latest version?

**Comment by Crzyrndm** [comment]
I'm looking into this

**Comment by Crzyrndm** [comment]
Cause found, should work for 3.0.1 release

**Comment by gomker** [comment]
Still seeing the issue in the latest release 

<img width="178" alt="screenshot0" src="https://user-images.githubusercontent.com/3577339/26892964-8a464662-4b7f-11e7-8aa6-3c7fb22f49d6.png">

**Comment by Crzyrndm** [comment]
-.-
Try again, dumb bug in the code loading those config nodes

**Comment by gomker** [comment]
Confirmed working, thanks very much.
Appreciate the quick response!
