### ISSUE TITLE
Question on category

### ISSUE THREAD

**Issue by gomker** [Crzyrndm/FilterExtension#74]
Is it permissible to have the same SUBCATEGORY set in two different configs? I have a "Naval" config and a "SMSolutions" config I am working on and the following seems to cancel each other out. Attaching the full configs

		SUBCATEGORY
		{
			name = SM Marine
			icon = smsolutions
			FILTER
			{
				CHECK
				{
					type = path
					value = SM_Marine
				}
			}
		}

https://www.dropbox.com/s/sg51g3kbde4gbg4/config.zip?dl=0

**Comment by Crzyrndm** [comment]
There should be an error (x1) in the log pointing out the duplication, but the first one loaded should still show up. Do they both disappear when the second one is added?

**Comment by gomker** [comment]
I do indeed see that error
     
     [ERR 22:52:38.974] [Filter Extensions 3.0.1]: subcategory name duplicated: SM Marine

They both disappear.  Is it just the "name" that has to be unique?

**Comment by Crzyrndm** [comment]
It is only checking against the subcategory title
